name: rso_events
description: Информационная система управления мероприятиями студенческих отрядов РСО
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^6.0.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_messaging: ^15.2.10
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
flutter_native_splash:
  color: "#a7bd6a"
  image: "assets/icon/icon_splash.png"
  android_12:
    color: "#a7bd6a"
    icon_background_color: "#a7bd6a"
    image: "assets/icon/icon_splash.png"
